### ISSUE TITLE
Gold/Silver/Bronze ordering in opened item

### ISSUE THREAD

**Issue by Extremedata** [pornganizer/PGV4#100]
The filtering uses the proper ordering of 123  but when opening a Category/Theme/DVD/Star/Website the order is 213

Simple things which makes the OCD kicks in and I really love having that 3rd type of liking option

**Comment by pornganizer** [comment]
![image](https://user-images.githubusercontent.com/21695807/31250689-a7b9011c-a9e9-11e7-9ab7-5b87907459a0.png)

**Comment by pornganizer** [comment]
lol sorry :s

**Comment by Extremedata** [comment]
No problem, I knew it was the idea of it all

stupid OCD lol will just take time to get used to before it stops getting annoying
