### ISSUE TITLE
Removing a category from a scene is not removing bookmarks

### ISSUE THREAD

**Issue by pornganizer** [pornganizer/PGV4#12]
Bookmarks need to be deleted when a category is removed from a scene as well as from PG.

**Comment by peinless** [comment]
Also because of bookmarks not getting deleted, you will have these empty bookmarks that you can't remove
![image](https://user-images.githubusercontent.com/31334325/29702098-d0af958a-896f-11e7-8f48-d4a35d317b39.png)
