### ISSUE TITLE
Import/export of Scene/DVD/Star data via CSV/XML/etc.

### ISSUE THREAD

**Issue by andromedary** [pornganizer/PGV4#36]
Is it possible to add functionality to import or export information for one or a group of Scenes/DVDs/Stars via small files such as CSV or XML? I've been using the webscraper.io plugin for Chrome to grab information for large volumes of my library, but data entry in PGV4 is a bottleneck (I suppose I can add information to the SQL file directly, but I don't want to mess around with things there too much). 

Importing and exporting could not only enable more efficient data entry, but it could eventually allow the PGV community to easily exchange data for popular Scenes/DVDs/Stars (ideal functionality could allow users to automatically query a repository of PGV metadata files created and submitted by other users, complementing/supplanting Starscraper functionality).

**Comment by pornganizer** [comment]
duplicate https://github.com/pornganizer/PGV4/issues/18
