### ISSUE TITLE
Scene info pane

### ISSUE THREAD

**Issue by ciaron88** [pornganizer/PGV4#48]
On the gray info area if you have so many stars tagged in the scene you can't see the Categories,themes, website area

![image](https://user-images.githubusercontent.com/31342057/29712725-29e7454e-8993-11e7-8669-773d768edc0d.png)

maybe after so many it should drop down to a 2nd row

**Comment by pornganizer** [comment]
duplicate https://github.com/pornganizer/PGV4/issues/30
