### ISSUE TITLE
When adding a "Splooges" PGv4 crashes.  Splooges are still recorded.

### ISSUE THREAD

**Issue by Cannon71** [pornganizer/PGV4#69]
PGv4 version 4.0.6457.28801

**Comment by pornganizer** [comment]
do you have discord integration setup?
i am not able to replicate this.

**Comment by Cannon71** [comment]
I do have Discord and I'm in the Pornganizer channel

**Comment by Cannon71** [comment]
Version=1
EventType=CLR20r3
EventTime=131498966483782045
ReportType=2
Consent=1
UploadTime=131498966641597019
ReportStatus=268435456
ReportIdentifier=5bb50520-eabe-4f79-ae7e-14d1d83fb95d
IntegratorReportIdentifier=b5a3577e-7a2f-486f-9551-bd4ea9f8f7c9
Wow64Host=34404
NsAppName=PGV4.exe
AppSessionGuid=0000176c-0001-0038-7d51-16849c2dd301
TargetAppId=W:0006221e8cca4f228c47cae95da2d8e18bb800000000!0000f6decf2614afd16d885da3af2022ae7536bb4c14!PGV4.exe
TargetAppVer=2017//09//05:20:00:04!0!PGV4.exe
BootId=4294967295
TargetAsId=1154
Response.BucketId=4870b1395ba458cb2e6c0254573a5dad
Response.BucketTable=5
Response.LegacyBucketId=129555792338
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=PGV4.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=4.0.6457.28801
Sig[2].Name=Problem Signature 03
Sig[2].Value=59af0244
Sig[3].Name=Problem Signature 04
Sig[3].Value=Discord.Net.Rest
Sig[4].Name=Problem Signature 05
Sig[4].Value=1.0.1.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=bc8d6998
Sig[6].Name=Problem Signature 07
Sig[6].Value=92b
Sig[7].Name=Problem Signature 08
Sig[7].Value=41d
Sig[8].Name=Problem Signature 09
Sig[8].Value=Discord.Net.HttpException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.15063.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=ed41
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=ed41b450c603bd0bb321749c8748da67
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=9c8a
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=9c8a019b164ce24850f445c2f10fcbe9
UI[2]=C:\Users\strik\Documents\Pornganizer v4\PGV4.exe
UI[3]=PGV4 has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Users\strik\Documents\Pornganizer v4\PGV4.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[11]=C:\WINDOWS\System32\combase.dll
LoadedModule[12]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[13]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[14]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[15]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[16]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[17]=C:\WINDOWS\System32\USER32.dll
LoadedModule[18]=C:\WINDOWS\System32\win32u.dll
LoadedModule[19]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[20]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[22]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[24]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\9aaf4ea9ded0a99b899b7bf4c971092d\mscorlib.ni.dll
LoadedModule[25]=C:\WINDOWS\System32\ole32.dll
LoadedModule[26]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[27]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[30]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[31]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[33]=C:\Users\strik\AppData\Local\Temp\Costura\458FE9F609400C7C674C687CC27F75FB\64\nreco.videoconverter.dll
LoadedModule[34]=C:\Users\strik\AppData\Local\Temp\Costura\458FE9F609400C7C674C687CC27F75FB\64\sqlite.interop.dll
LoadedModule[35]=C:\Users\strik\AppData\Local\Temp\Costura\458FE9F609400C7C674C687CC27F75FB\64\sqlite.net.platform.win32.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\dwrite.dll
LoadedModule[37]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[38]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\D3DCOMPILER_47.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\MSVCP120_CLR0400.dll
LoadedModule[41]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[42]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[44]=C:\WINDOWS\System32\shcore.dll
LoadedModule[45]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[46]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[47]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[48]=C:\WINDOWS\System32\profapi.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[50]=C:\WINDOWS\SYSTEM32\msiso.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[52]=C:\WINDOWS\System32\shell32.dll
LoadedModule[53]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[54]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\iphlpapi.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[57]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[58]=C:\WINDOWS\System32\NSI.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[60]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[61]=C:\WINDOWS\SYSTEM32\WINNSI.DLL
LoadedModule[62]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[64]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_ce1961376673184c\nvldumdx.dll
LoadedModule[65]=C:\WINDOWS\System32\crypt32.dll
LoadedModule[66]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[67]=C:\WINDOWS\System32\WINTRUST.DLL
LoadedModule[68]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[69]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_ce1961376673184c\nvd3dumx.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\winmmbase.dll
LoadedModule[72]=C:\WINDOWS\system32\nvspcap64.dll
LoadedModule[73]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[74]=C:\WINDOWS\System32\PSAPI.DLL
LoadedModule[75]=C:\WINDOWS\SYSTEM32\WINHTTP.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[77]=C:\WINDOWS\system32\nvapi64.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\dxgi.dll
LoadedModule[79]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\Wininet.dll
LoadedModule[81]=C:\WINDOWS\SYSTEM32\rasapi32.dll
LoadedModule[82]=C:\WINDOWS\SYSTEM32\rasman.dll
LoadedModule[83]=C:\WINDOWS\SYSTEM32\rtutils.dll
LoadedModule[84]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
LoadedModule[86]=C:\Windows\System32\rasadhlp.dll
LoadedModule[87]=C:\WINDOWS\System32\fwpuclnt.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\secur32.dll
LoadedModule[89]=C:\WINDOWS\system32\schannel.DLL
LoadedModule[90]=C:\WINDOWS\SYSTEM32\mskeyprotect.dll
LoadedModule[91]=C:\WINDOWS\SYSTEM32\ncrypt.dll
LoadedModule[92]=C:\WINDOWS\SYSTEM32\NTASN1.dll
LoadedModule[93]=C:\WINDOWS\system32\ncryptsslp.dll
LoadedModule[94]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\dxva2.dll
LoadedModule[96]=C:\WINDOWS\system32\wmp.dll
LoadedModule[97]=C:\WINDOWS\system32\mfperfhelper.dll
LoadedModule[98]=C:\WINDOWS\system32\WMVCore.DLL
LoadedModule[99]=C:\WINDOWS\system32\WMASF.DLL
LoadedModule[100]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.15063.608_none_56f0266b425534e9\gdiplus.dll
LoadedModule[101]=C:\WINDOWS\SYSTEM32\MFPlat.DLL
LoadedModule[102]=C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
LoadedModule[103]=C:\WINDOWS\system32\wmploc.dll
LoadedModule[104]=C:\WINDOWS\System32\MMDevApi.dll
LoadedModule[105]=C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
LoadedModule[106]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[107]=C:\WINDOWS\SYSTEM32\AVRT.dll
LoadedModule[108]=C:\Windows\System32\Windows.UI.dll
LoadedModule[109]=C:\Windows\System32\TextInputFramework.dll
LoadedModule[110]=C:\Windows\System32\CoreUIComponents.dll
LoadedModule[111]=C:\Windows\System32\CoreMessaging.dll
LoadedModule[112]=C:\WINDOWS\SYSTEM32\usermgrcli.dll
LoadedModule[113]=C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[114]=C:\WINDOWS\SYSTEM32\WINSTA.dll
LoadedModule[115]=C:\WINDOWS\system32\websocket.dll
LoadedModule[116]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[117]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[118]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[119]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[120]=C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI64.dll
LoadedModule[121]=C:\Users\strik\Documents\Pornganizer v4\SQLite.Interop.dll
LoadedModule[122]=C:\WINDOWS\SYSTEM32\UIAutomationCore.dll
LoadedModule[123]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[124]=C:\WINDOWS\system32\msctfui.dll
LoadedModule[125]=C:\Program Files (x86)\DisplayFusion\Hooks\AppHook64_E41EBE74-A675-4F10-93D7-F6D400CA12B7.dll
LoadedModule[126]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.15063.413_none_0e0f5dcc67adff4e\COMCTL32.dll
LoadedModule[127]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[128]=C:\WINDOWS\system32\NetworkExplorer.dll
LoadedModule[129]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[130]=C:\WINDOWS\System32\drprov.dll
LoadedModule[131]=C:\WINDOWS\System32\ntlanman.dll
LoadedModule[132]=C:\WINDOWS\System32\davclnt.dll
LoadedModule[133]=C:\WINDOWS\System32\DAVHLPR.dll
LoadedModule[134]=C:\WINDOWS\System32\netutils.dll
LoadedModule[135]=C:\WINDOWS\SYSTEM32\cscapi.dll
LoadedModule[136]=C:\WINDOWS\System32\srvcli.dll
LoadedModule[137]=C:\Windows\System32\thumbcache.dll
LoadedModule[138]=C:\WINDOWS\SYSTEM32\edputil.dll
LoadedModule[139]=C:\Windows\System32\Windows.StateRepository.dll
LoadedModule[140]=C:\Windows\System32\StateRepository.Core.dll
LoadedModule[141]=C:\WINDOWS\SYSTEM32\PhotoMetadataHandler.dll
LoadedModule[142]=C:\WINDOWS\SYSTEM32\atlthunk.dll
LoadedModule[143]=C:\WINDOWS\system32\MF.dll
LoadedModule[144]=C:\WINDOWS\system32\MFTranscode.DLL
LoadedModule[145]=C:\WINDOWS\system32\MFCORE.DLL
LoadedModule[146]=C:\WINDOWS\system32\ksuser.dll
LoadedModule[147]=C:\Windows\System32\wmpeffects.dll
LoadedModule[148]=C:\Windows\System32\msdmo.dll
LoadedModule[149]=C:\WINDOWS\System32\mfmp4srcsnk.dll
LoadedModule[150]=C:\WINDOWS\system32\mfasfsrcsnk.dll
LoadedModule[151]=C:\WINDOWS\system32\mlang.dll
LoadedModule[152]=C:\WINDOWS\system32\EVR.dll
LoadedModule[153]=C:\Windows\System32\Windows.ApplicationModel.dll
LoadedModule[154]=C:\Windows\System32\AppXDeploymentClient.dll
LoadedModule[155]=C:\WINDOWS\SYSTEM32\CompPkgSup.DLL
LoadedModule[156]=C:\Windows\System32\MSAudDecMFT.dll
LoadedModule[157]=C:\Windows\System32\resampledmo.dll
LoadedModule[158]=C:\Windows\System32\colorcnv.dll
LoadedModule[159]=C:\Windows\System32\mp4sdecd.dll
LoadedModule[160]=C:\Windows\System32\mfps.dll
LoadedModule[161]=C:\Windows\System32\Windows.Media.MediaControl.dll
LoadedModule[162]=C:\WINDOWS\SYSTEM32\OLEACC.dll
LoadedModule[163]=C:\Windows\System32\WMADMOD.DLL
LoadedModule[164]=C:\Windows\System32\wmvdecod.dll
LoadedModule[165]=C:\Windows\System32\msmpeg2vdec.dll
LoadedModule[166]=C:\WINDOWS\system32\windowscodecsext.dll
LoadedModule[167]=C:\Windows\System32\msxml6.dll
LoadedModule[168]=C:\WINDOWS\SYSTEM32\mscms.dll
LoadedModule[169]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[170]=C:\WINDOWS\SYSTEM32\icm32.dll
LoadedModule[171]=C:\WINDOWS\System32\provsvc.dll
LoadedModule[172]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=PGV4
AppPath=C:\Users\strik\Documents\Pornganizer v4\PGV4.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=39C4D120109066E230F2C168935ECA4A
MetadataHash=1204054767

**Comment by pornganizer** [comment]
try now

**Comment by Cannon71** [comment]
working now.  Thanks!!
