### ISSUE TITLE
Player path not being saved after restart

### ISSUE THREAD

**Issue by sjclayton** [pornganizer/PGV4#72]
Setting the media player path (for MPC specifically) does not get saved on relaunch. Don't know if this affects VLC as well as I have not tried it.

**Comment by pornganizer** [comment]
this should be fixed in latest version

**Comment by sjclayton** [comment]
@pornganizer The latest version is the one posted here https://github.com/pornganizer/PGV4/releases/latest ..? if so, it is not fixed in that version.

**Comment by sjclayton** [comment]
clearly you can't see posts / mentions after you closed the issue.... IDK why you wouldn't be able to...

it is not working in the version that is available here on Github, so the issue shouldn't have been closed.. if you are referring to some other version, then that's fine, but I'd figured you'd release the update here if so.
