### ISSUE TITLE
Error Loading Database

### ISSUE THREAD

**Issue by tmoserly** [pornganizer/PGV4#76]
After random crash while editing DVD entries (specifically adding an image iirc), PGV4 now hangs on "Loading Database" with an "Error Loading Database: Constructor on type 'PG.Core.Models.Join_Tables.Dvds.DvdWebsite' not found." message in the log.

There are also roughly a hundred "Error getting directories for X is denied." messages, but these persist with a new database and don't seem to inhibit launch.

**Comment by pornganizer** [comment]
i can't really explain the dvdwebsite error.  somehow you glitched out the tagging system to create a tag that shouldnt exist?  that is my best guess

what folders are throwing access denied? i know there might be a few but a hundred seems like a lot

**Comment by tmoserly** [comment]
Is there any action I can take to recover, some way to edit the .db? Or do I just have to scrap the database and start over?

This is the first of roughly ten pages of the log. The lion's share of the messages are from E:\ProgramData, though it hits E:\Users and E:\Windows as well. The last is for E:\Windows\Temp. The first four errors come up pretty much instantly along with the stack trace. Then there's maybe thirty seconds lag, the next two come up, and then the rest a few seconds later. It's also worth noting that PVG itself, along with the database and all the files it's using are located on my F: drive, for which there are no messages.
![image](https://user-images.githubusercontent.com/32017196/30546801-98b48b0a-9c5b-11e7-94d8-a5ae085a681f.png)

**Comment by pornganizer** [comment]
try removing all the records from the DvdWebsites table

this table should actually not exist.  i am curious as to how you managed to get an entry in there.  i am going through my code now and removing references to it.  the websites listed in dvd details should be a unique list of all the websites of all the scenes for that dvd.

**Comment by pornganizer** [comment]
ive also added all those folders to my ignore list, so next version should drastically cut down on those errors

**Comment by pornganizer** [comment]
https://github.com/pornganizer/PGV4/issues/88

**Comment by framedevelop** [comment]
![image](https://user-images.githubusercontent.com/33002540/32137626-9cc8da9c-bbf1-11e7-833e-bd7858254dc0.png)

I am not sure if this is the exact same error but seems similar. I was adding websites to clips and closed the application when I was done. When reloading, I get the following errors in the log and it hangs at the "loading database" splash screen. 

Is there any way for me to save my database?

**Comment by framedevelop** [comment]
I followed the instructions under #76 and fixed the issue by removing entries from WebsiteWebsite table using sqllitebrowser. Just thought you should know that this can happen in this setting as well.
