### ISSUE TITLE
Can't use the blue highlighted text in uppercase

### ISSUE THREAD

**Issue by Kioo30** [pornganizer/PGV4#79]
When I open PGV4 v4.0.6457.28801 I get the popup where I get the possibility to click CONVERT PGV3 DATABASE. But when I click it nothing happens. Creating a new PGV3 database instead works flawless.

I'm using Windows 8.1 with these installed .NET Framework Versions: 2.0.50727, 3.0, 3.5, 4.0, 4.7

Edit:
So I noticed, that I can't use any of blue highlighted text in upper case.

**Comment by pornganizer** [comment]
you'll need to download the converter exe and place it next to the pgv4 exe

**Comment by Kioo30** [comment]
That and a reboot fix all the mentioned problems here.

To prevent that, maybe use in future versions a popup to notify the user about the missing executable.
