### ISSUE TITLE
UI won't fit in height

### ISSUE THREAD

**Issue by Kioo30** [pornganizer/PGV4#80]
I don't know reason for that bug, but I already had it with PGV3.
On my PC, which has a resolution of 1920x1080, a part of the app (v4.0.6457.28801) can't get displayed. 
For some reason, it is not possible to decrease the height of the PGV4 window so manual adjustion is not possible. Even maximizing the window isn't helping, a part always gets cut off. Someone else experiencing that bug?

At the end some pictures to demonstrate the problem:
Default window size:
![2](https://user-images.githubusercontent.com/32024748/30516674-c7d62176-9b45-11e7-8ce6-6f288070e6b1.jpg)
Maximized window:
![1](https://user-images.githubusercontent.com/32024748/30516690-6a6e61dc-9b46-11e7-94ba-79438ed7a28f.jpg)

I'm using Windows 8.1 with these .NET Framework Versions: 2.0.50727, 3.0, 3.5, 4.0, 4.7

**Comment by pornganizer** [comment]
do you have windows set to scale your apps larger or something?
this is very weird

**Comment by Kioo30** [comment]
Yes, your right. My default scaling is 150%, setting it to 125% fixed it.

(In Windows 8.1's “Appearance and Personalization”:
![windows_2d00_8_2d00_dpi_2d00_scaling_2d00_cpl_2d00_crop_5f00_58c2f130](https://user-images.githubusercontent.com/32024748/30519702-09df82b8-9b9d-11e7-9045-e30865aa8398.jpg)
Source:
https://blogs.windows.com/windowsexperience/2013/07/15/windows-8-1-dpi-scaling-enhancements/)

----

The only problem now is, that even 125% is quite small on a 12" laptop, maybe there is a other way to fix it?

**Comment by pornganizer** [comment]
maybe you shouldnt run at 1080 resolution if you find things too small.

125% is the default and most people wouldn't change it.

PG needs a minimum height to fit all the controls, hence your issue.

**Comment by Kioo30** [comment]
Okay thank you.  Keep up the good work.
