### ISSUE TITLE
Enhancement Request: Arrow Button Navigation 

### ISSUE THREAD

**Issue by Extremedata** [pornganizer/PGV4#83]
Is it possible the implement something to navigate up and down with the arrow keys until the scrolling and scroll bar issues has been resolved?

**Comment by pornganizer** [comment]
use PageUp and PageDown or click the scrollbar itself instead of trying to drag the thumb-tack
that is as good as it is going to get for a while. arrow keys will already navigate the selected item.

**Comment by Extremedata** [comment]
Scrolling issue bieng fixed there is no need for this enhancement
